Sensor_App/Sensor_App/Models/Cliente.cs
using Sensor_App.Models.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sensor_App.Models
{
    public class Cliente
    {
        public Cliente()
        {
            //Seguro = new HashSet<Seguro>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int ClienteId { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Razon social")]
        public string RazonSocial { get; set; }

        [Required]
        [Display(Name = "Nro RUC")]
        public int NroRuc { get; set; }

        [Required]
        [StringLength(30)]
        public string Direccion { get; set; }

        [Required]
        [StringLength(30)]
        public string Pais { get; set; }

        [Required]
        [StringLength(30)]
        public string Ciudad { get; set; }

        [Required]
        [Display(Name = "Codigo postal")]
        public int CodPostal { get; set; }

        [Required]
        public ZonaEnum Zona { get; set; }

        [Required]
        [StringLength(30)]
        public string Telefono { get; set; }

        [Required]
        [StringLength(30)]
        public string Fax { get; set; }

        [Required]
        [StringLength(30)]
        public string Email { get; set; }

        [Required]
        [StringLength(30)]
        public string Web { get; set; }

        public ICollection<Seguro> Seguro { get; set; }
        //[ForeignKey("SeguroID")]
        //public Seguro Seguro { get; set; }
        //[Key]
        //public int IdSeguro { get; set; }
        //public virtual Seguro Seguro { get; set; }
        //public int ClienteID { get; set; }

        [Required]
        [StringLength(30)]
        public bool Activo { get; set; }
    }
}

Sensor_App/Sensor_App/Controllers/ClienteController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sensor_App.Interfaces;
using Sensor_App.Models;
using Sensor_App.Models.Enums;

namespace Sensor_App.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ClienteController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize(Roles = "Listado_Cliente")]
        [HttpGet]
        public async Task<ActionResult> ListaClientes()
        {
            var clientes = await _unitOfWork.ClienteRepository.GetAllClientesAsync();
            return View(clientes);
        }
        [Authorize(Roles = "Alta_Cliente")]
        [HttpGet]
        public ActionResult Crear(int id = 0)
        {
            return View(new Cliente());
        }
        [HttpPost]
        [Authorize(Roles = "Alta_Cliente")]
        public async Task<ActionResult> Crear(int id, string RazonSocial, int NroRuc, string Direccion, string Pais, string Ciudad, int CodPostal, ZonaEnum Zona, string Telefono, string Fax, string Email, string Web, EstadoTransitoEnum uruguayTransito, EstadoTransitoEnum cargaSuelta, bool Activo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Cliente cliente = new Cliente
                    {
                        RazonSocial = RazonSocial,
                        NroRuc = NroRuc,
                        Direccion = Direccion,
                        Pais = Pais,
                        Ciudad = Ciudad,
                        CodPostal = CodPostal,
                        Zona = Zona,
                        Telefono = Telefono,
                        Fax = Fax,
                        Email = Email,
                        Web = Web,
                        Activo = Activo
                    };

                    if (id == 0)
                    {
                        await _unitOfWork.ClienteRepository.Add(cliente);
                        await _unitOfWork.SaveChangesAsync();
                        //var res = _unitOfWork.ClienteRepository.
                        Seguro seguro = new Seguro
                        {
                            ClienteId = cliente.ClienteId,
                            Uruguay_Transitos = uruguayTransito,
                            Uruguay_Transitos_Carga_Suelta = cargaSuelta
                        };
                        await _unitOfWork.SeguroRepository.Add(seguro);
                        await _unitOfWork.SaveChangesAsync();
                    }
                    return Json(new { isValid = true });
                }
                return Json(new { isValid = false });
            }
            catch (Exception e)
            {

                return Json(new { isValid = false });
            }

        }

        [Authorize(Roles = "Modificacion_Cliente")]
        [HttpGet]
        public async Task<ActionResult> Editar(int id = 0)
        {
            if (id == 0)
            {
                return View(new User());
            }
            else
            {
                var user = await _unitOfWork.ClienteRepository.GetClienteByIdAsync(id);
                return View(user);
            }

        }
        [Authorize(Roles = "Modificacion_Cliente")]
        [HttpPost]
        public async Task<ActionResult> Editar(int id, string RazonSocial, int NroRuc, string Direccion, string Pais, string Ciudad, int CodPostal, ZonaEnum Zona, string Telefono, string Fax, string Email, string Web, EstadoTransitoEnum uruguayTransito, EstadoTransitoEnum cargaSuelta, bool Activo)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    Cliente cliente = new Cliente
                    {
                        ClienteId = id,
                        RazonSocial = RazonSocial,
                        NroRuc = NroRuc,
                        Direccion = Direccion,
                        Pais = Pais,
                        Ciudad = Ciudad,
                        CodPostal = CodPostal,
                        Zona = Zona,
                        Telefono = Telefono,
                        Fax = Fax,
                        Email = Email,
                        Web = Web,
                        Activo = Activo
                    };

                    _unitOfWork.ClienteRepository.Update(cliente);
                    await _unitOfWork.SaveChangesAsync();
                    await _unitOfWork.SeguroRepository.CleanSeguros(cliente.ClienteId);
                    Seguro seguro = new Seguro
                    {
                        ClienteId = cliente.ClienteId,
                        Uruguay_Transitos = uruguayTransito,
                        Uruguay_Transitos_Carga_Suelta = cargaSuelta
                    };
                    await _unitOfWork.SeguroRepository.Add(seguro);
                    await _unitOfWork.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return NotFound();
                }

                return Json(new { isValid = true });


            }
            return Json(new { isValid = false });
        }

        [HttpPost]
        [Authorize(Roles = "Baja_Cliente")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarCliente(int id)
        {
            try
            {
                //var user = _unitOfWork.UserRepository.GetUserByIdAsync(id);
                await _unitOfWork.ClienteRepository.Delete(id);
                await _unitOfWork.SaveChangesAsync();
                await _unitOfWork.SeguroRepository.CleanSeguros(id);
                return Json(new { isValid = true });

            }
            catch (Exception e)
            {
                return Json(new { isValid = false });
            }

        }
    }
}

Sensor_App/Sensor_App/Controllers/UserController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sensor_App.BusinessLogic;
using Sensor_App.Interfaces;
using Sensor_App.Models;

namespace Sensor_App.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginUserModel user)
        {
            string resultado = "Fail";

            var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
            user.Contrasenia = passwordEncriptada;

            var getUser = await _unitOfWork.UserRepository.AuthenticationAsync(user.Usuario, user.Contrasenia);
            if (getUser != null)
            {
                ClaimsIdentity identity = null;
                identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Name, getUser.NombreUsuario),
                    new Claim(ClaimTypes.Role,"Admin")
                }, CookieAuthenticationDefaults.AuthenticationScheme);
                foreach (var item in getUser.Permisos)
                {
                    identity.AddClaim(new Claim(ClaimTypes.Role, item.Permiso.ToString()));
                }
                var principal = new ClaimsPrincipal(identity);
                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                HttpContext.Session.SetString("LoginName", getUser.Nombre);
                resultado = "Sucess";
            }
            return Json(resultado);
        }
        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            var resultado = "Fail";
            try
            {
                await HttpContext.SignOutAsync();
                HttpContext.Session.Clear();
                resultado = "Success";
                return Json(resultado);
            }
            catch (Exception e)
            {

                return Json(resultado);
            }

        }

        [HttpGet]
        public IActionResult Inicio()
        {
            return View();
        }

        [Authorize(Roles = "Listado_Usuario")]
        [HttpGet]
        public async Task<ActionResult> ListaUsuarios()
        {
            var users = await _unitOfWork.UserRepository.GetAllUsersAsync();
            return View(users);
        }

        //FUERA DE USO
        //[Authorize(Roles = "Alta_Usuario, Modificacion_Usuario")]
        //[HttpGet]
        //public async Task<ActionResult> CrearOEditar(int id = 0)
        //{
        //    if (id == 0)
        //    {
        //        return View(new User());
        //    }
        //    else
        //    {
        //        var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
        //        return View(user);
        //    }

        //}
        [Authorize(Roles = "Alta_Usuario")]
        [HttpGet]
        public async Task<ActionResult> Crear(int id = 0)
        {
            if (id == 0)
            {
                return View(new User());
            }
            else
            {
                var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
                return View(user);
            }

        }
        [Authorize(Roles = "Modificacion_Usuario")]
        [HttpGet]
        public async Task<ActionResult> Editar(int id = 0)
        {
            if (id == 0)
            {
                return View(new User());
            }
            else
            {
                var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
                return View(user);
            }

        }

        //FUERA DE USO
        //[Authorize(Roles = "Alta_Usuario, Modificacion_Usuario")]
        //[HttpPost]
        //public async Task<ActionResult> CrearOEditar(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (id == 0)
        //        {
        //            //GET CLIENTE
        //            //var cliente = await _unitOfWork.ClienteRepository.GetById(Int32.Parse(Cliente));
        //            //PERMISOS
        //            user.ClienteID = Int32.Parse(Cliente);
        //            await _unitOfWork.UserRepository.Add(user);
        //            await _unitOfWork.SaveChangesAsync();
        //            await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
        //        }
        //        else
        //        {
        //            try
        //            {
        //                user.ClienteID = Int32.Parse(Cliente);
        //                _unitOfWork.UserRepository.Update(user);
        //                await _unitOfWork.SaveChangesAsync();
        //                await _unitOfWork.PermisoTipoRepository.CleanPermisos(user.Id);
        //                await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
        //            }
        //            catch (Exception)
        //            {
        //                return NotFound();
        //            }
        //        }
        //        return Json(new { isValid = true });
        //    }
        //    return Json(new { isValid = false });
        //}

        [Authorize(Roles = "Modificacion_Usuario")]
        [HttpPost]
        public async Task<ActionResult> Editar(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        {
            if (ModelState.IsValid)
            {
                if (id != 0)
                {
                    try
                    {
                        user.ClienteID = Int32.Parse(Cliente);

                        var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
                        user.Contrasenia = passwordEncriptada;

                        _unitOfWork.UserRepository.Update(user);
                        await _unitOfWork.SaveChangesAsync();

                        await _unitOfWork.PermisoTipoRepository.CleanPermisos(user.Id);
                        await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
                    }
                    catch (Exception)
                    {
                        return NotFound();
                    }

                    return Json(new { isValid = true });
                }
                
            }
            return Json(new { isValid = false });
        }

        [Authorize(Roles = "Alta_Usuario")]
        [HttpPost]
        public async Task<ActionResult> Crear(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    user.ClienteID = Int32.Parse(Cliente);

                    var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
                    user.Contrasenia = passwordEncriptada;

                    await _unitOfWork.UserRepository.Add(user);
                    await _unitOfWork.SaveChangesAsync();

                    await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
                }
                return Json(new { isValid = true });
            }
            return Json(new { isValid = false });
        }
        [HttpPost]
        [Authorize(Roles = "Baja_Usuario")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarUsuario(int id)
        {
            try
            {
                await _unitOfWork.UserRepository.Delete(id);
                await _unitOfWork.SaveChangesAsync();

                await _unitOfWork.PermisoTipoRepository.CleanPermisos(id);
                return Json(new { isValid = true });

            }
            catch (Exception e)
            {
                return Json(new { isValid = false });
            }

        }


    }
}

Sensor_App/Sensor_App/Views/Cliente/Crear.cshtml
@model Sensor_App.Models.Cliente
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Crear" asp-route-id="@Model.ClienteId" onsubmit="return jQueryAjaxPostCliente(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClienteId" />
            <div class="form-group row">
                <label asp-for="RazonSocial" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="NroRuc" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-3">
                    <input asp-for="NroRuc" class="form-control" />
                    <span asp-validation-for="NroRuc" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Direccion" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Pais" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <select class="pais-selector" name="Pais">
                        <option value="Argentina">Argentina</option>
                        <option value="Uruguay">Uruguay</option>
                        <option value="Brasil">Brasil</option>
                        <option value="USA">USA</option>
                        <option value="China">China</option>
                        <option value="Alemania">Alemania</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Ciudad" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Ciudad" class="form-control" />
                    <span asp-validation-for="Ciudad" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="CodPostal" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="CodPostal" class="form-control" />
                    <span asp-validation-for="CodPostal" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Zona" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-5">
                    <select asp-for="Zona" class="form-control">
                        <option value="0">Norte</option>
                        <option value="1">Centro</option>
                        <option value="2">Sur</option>
                    </select>
                    <span asp-validation-for="Zona" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Telefono" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-3">
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Fax" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-3">
                    <input asp-for="Fax" class="form-control" />
                    <span asp-validation-for="Fax" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Email" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="Web" class="control-label col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Web" class="form-control" />
                    <span asp-validation-for="Web" class="text-danger"></span>
                </div>
            </div>

            <fieldset>
                <legend>Seguro</legend>
                <div class="row bg-light text-dark">
                    <div class="col-sm-6 border border-dark">
                        Descripcion
                    </div>
                    <div class="col-sm-2 border border-dark">
                        Si
                    </div>
                    <div class="col-sm-2 border border-dark">
                        No
                    </div>
                    <div class="col-sm-2 border border-dark">
                        Opcional
                    </div>
                </div>
                <div class="row ">
                    <div class="col-sm-6 border border-dark">
                        Uruguay - Transitos
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="uruguayTransito" value="0" aria-label="...">
                        </div>
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="uruguayTransito" value="1" aria-label="...">
                        </div>
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="uruguayTransito" value="2" aria-label="...">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 border border-dark">
                        Uruguay - Transitos carga suelta
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="cargaSuelta" value="0" aria-label="...">
                        </div>
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="cargaSuelta" value="1" aria-label="...">
                        </div>
                    </div>
                    <div class="col-sm-2 border border-dark">
                        <div class="form-check">
                            <input class="form-check-input position-static" type="radio" name="cargaSuelta" value="2" aria-label="...">
                        </div>
                    </div>
                </div>
            </fieldset>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/js/userAjax.js"></script>
<script>
    $(document).ready(function () {
        $('.pais-selector').select2();
    });
</script>

Sensor_App/Sensor_App/Views/Cliente/ListaClientes.cshtml
@model IEnumerable<Sensor_App.Models.Cliente>

@{
    ViewData["Title"] = "Lista clientes";
}
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <link href="~/assets/css/app.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->
</head>

<h1>Lista de Clientes</h1>

<p>
    <button type="button" class="btn btn-primary" id="crerUserButton" onclick="showInPopup('@Url.Action("Crear","Cliente", null, Context.Request.Scheme)', 'Crear cliente')">Crear Cliente</button>
</p>
<table id="table_id" class="table display">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RazonSocial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NroRuc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ciudad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodPostal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zona)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Web)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th>
                Uruguay - Transitos
            </th>
            <th>
                Uruguay - Transitos carga suelta
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RazonSocial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NroRuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodPostal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Web)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            @foreach (var seguro in item.Seguro)
            {
                <td>
                    @seguro.Uruguay_Transitos
                </td>
                <td>
                    @seguro.Uruguay_Transitos_Carga_Suelta
                </td>
            }
            <td>
                <a onclick="showInPopup('@Url.Action("Editar", "Cliente", new { id = item.ClienteId}, Context.Request.Scheme)', 'Modificar cliente')" class="btn btn-info text-white">Editar</a> |
                <form asp-action="EliminarCliente" asp-route-id="@item.ClienteId" onsubmit="return jQueryAjaxDeleteCliente(this);" class="d-inline">
                    <input type="submit" value="Eliminar" class="btn btn-danger" />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>


<div>
    <button type="button" onclick="@("window.location.href='" + @Url.Action("Inicio", "User") + "'");" class="btn btn-primary">Volver a inicio</button>
</div>
<!-- ================== BEGIN BASE JS ================== -->

<script src="~/js/theme/default.min.js"></script>
<script src="~/js/site.js"></script>
<script src="~/js/userAjax.js"></script>
<!-- ================== END BASE JS ================== -->