Sensor_App/Sensor_App/Models/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sensor_App.Models
{
    public class User
    {
        public User()
        {
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required(ErrorMessage ="Este campo es requerido")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(30)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(50)]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(20)]
        [Display(Name = "Nombre Usuario")]
        public string NombreUsuario { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(100)]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string Contrasenia { get; set; }

        public virtual ICollection<PermisoTipo> Permisos { get; set; }
        //[Key]
        //public int IdCliente { get; set; }
        public virtual Cliente Cliente { get; set; }

        //[ForeignKey("ClienteID")]
        //public Cliente Cliente {get;set;}
        public int ClienteID { get; set; }

        //[ForeignKey("PermisosID")]
        //[Required]
        //public Permisos Permisos {get;set;}
        //public int PermisosID { get; set; }
    }
}

Sensor_App/Sensor_App/Models/ViewModel/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Sensor_App.Models.ViewModel
{
    public class UserViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(30)]
        public string Nombre { get; set; }

        [Required]
        [StringLength(50)]
        public string Descripcion { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Nobre Usuario")]
        public string NombreUsuario { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Contraseña")]
        public string Contrasenia { get; set; }

        public virtual ICollection<PermisoTipo> Permisos { get; set; }

        public virtual Cliente Cliente { get; set; }
    }
}

Sensor_App/Sensor_App/Controllers/MapaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Sensor_App.Controllers
{
    public class MapaController : Controller
    {
        [Authorize(Roles = "Visualizacion_Mapa")]
        public IActionResult VerMapa()
        {
            return View();
        }
    }
}

Sensor_App/Sensor_App/Controllers/UserController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sensor_App.BusinessLogic;
using Sensor_App.Interfaces;
using Sensor_App.Models;

namespace Sensor_App.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginUserModel user)
        {
            string resultado = "Fail";

            var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
            user.Contrasenia = passwordEncriptada;

            var getUser = await _unitOfWork.UserRepository.AuthenticationAsync(user.Usuario, user.Contrasenia);
            if (getUser != null)
            {
                ClaimsIdentity identity = null;
                identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Name, getUser.NombreUsuario),
                    new Claim(ClaimTypes.Role,"Admin")
                }, CookieAuthenticationDefaults.AuthenticationScheme);
                foreach (var item in getUser.Permisos)
                {
                    identity.AddClaim(new Claim(ClaimTypes.Role, item.Permiso.ToString()));
                }
                var principal = new ClaimsPrincipal(identity);
                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                HttpContext.Session.SetString("LoginName", getUser.Nombre);
                resultado = "Sucess";
            }
            return Json(resultado);
        }
        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            var resultado = "Fail";
            try
            {
                await HttpContext.SignOutAsync();
                HttpContext.Session.Clear();
                resultado = "Success";
                return Json(resultado);
            }
            catch (Exception e)
            {

                return Json(resultado);
            }

        }

        [HttpGet]
        public IActionResult Inicio()
        {
            return View();
        }

        [Authorize(Roles = "Listado_Usuario")]
        [HttpGet]
        public async Task<ActionResult> ListaUsuarios()
        {
            var users = await _unitOfWork.UserRepository.GetAllUsersAsync();
            return View(users);
        }

        //FUERA DE USO
        //[Authorize(Roles = "Alta_Usuario, Modificacion_Usuario")]
        //[HttpGet]
        //public async Task<ActionResult> CrearOEditar(int id = 0)
        //{
        //    if (id == 0)
        //    {
        //        return View(new User());
        //    }
        //    else
        //    {
        //        var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
        //        return View(user);
        //    }

        //}
        [Authorize(Roles = "Alta_Usuario")]
        [HttpGet]
        public async Task<ActionResult> Crear(int id = 0)
        {
            if (id == 0)
            {
                return View(new User());
            }
            else
            {
                var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
                return View(user);
            }

        }
        [Authorize(Roles = "Modificacion_Usuario")]
        [HttpGet]
        public async Task<ActionResult> Editar(int id = 0)
        {
            if (id == 0)
            {
                return View(new User());
            }
            else
            {
                var user = await _unitOfWork.UserRepository.GetUserByIdAsync(id);
                return View(user);
            }

        }

        //FUERA DE USO
        //[Authorize(Roles = "Alta_Usuario, Modificacion_Usuario")]
        //[HttpPost]
        //public async Task<ActionResult> CrearOEditar(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (id == 0)
        //        {
        //            //GET CLIENTE
        //            //var cliente = await _unitOfWork.ClienteRepository.GetById(Int32.Parse(Cliente));
        //            //PERMISOS
        //            user.ClienteID = Int32.Parse(Cliente);
        //            await _unitOfWork.UserRepository.Add(user);
        //            await _unitOfWork.SaveChangesAsync();
        //            await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
        //        }
        //        else
        //        {
        //            try
        //            {
        //                user.ClienteID = Int32.Parse(Cliente);
        //                _unitOfWork.UserRepository.Update(user);
        //                await _unitOfWork.SaveChangesAsync();
        //                await _unitOfWork.PermisoTipoRepository.CleanPermisos(user.Id);
        //                await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
        //            }
        //            catch (Exception)
        //            {
        //                return NotFound();
        //            }
        //        }
        //        return Json(new { isValid = true });
        //    }
        //    return Json(new { isValid = false });
        //}

        [Authorize(Roles = "Modificacion_Usuario")]
        [HttpPost]
        public async Task<ActionResult> Editar(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        {
            if (ModelState.IsValid)
            {
                if (id != 0)
                {
                    try
                    {
                        user.ClienteID = Int32.Parse(Cliente);

                        var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
                        user.Contrasenia = passwordEncriptada;

                        _unitOfWork.UserRepository.Update(user);
                        await _unitOfWork.SaveChangesAsync();

                        await _unitOfWork.PermisoTipoRepository.CleanPermisos(user.Id);
                        await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
                    }
                    catch (Exception)
                    {
                        return NotFound();
                    }

                    return Json(new { isValid = true });
                }
                
            }
            return Json(new { isValid = false });
        }

        [Authorize(Roles = "Alta_Usuario")]
        [HttpPost]
        public async Task<ActionResult> Crear(int id, [Bind("Id, Nombre, Descripcion, NombreUsuario, Contrasenia, Cliente, Permisos")] User user, string Cliente, string[] Permisos)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    user.ClienteID = Int32.Parse(Cliente);

                    var passwordEncriptada = PasswordHandler.GetSHA256(user.Contrasenia);
                    user.Contrasenia = passwordEncriptada;

                    await _unitOfWork.UserRepository.Add(user);
                    await _unitOfWork.SaveChangesAsync();

                    await _unitOfWork.PermisoTipoRepository.AddParameterizedPermiso(Permisos, user.Id);
                }
                return Json(new { isValid = true });
            }
            return Json(new { isValid = false });
        }
        [HttpPost]
        [Authorize(Roles = "Baja_Usuario")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarUsuario(int id)
        {
            try
            {
                await _unitOfWork.UserRepository.Delete(id);
                await _unitOfWork.SaveChangesAsync();

                await _unitOfWork.PermisoTipoRepository.CleanPermisos(id);
                return Json(new { isValid = true });

            }
            catch (Exception e)
            {
                return Json(new { isValid = false });
            }

        }


    }
}

Sensor_App/Sensor_App/ViewComponent/ListaClientesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sensor_App.DBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace ViewComponentSample.ViewComponents
{
    public class ListaClientesViewComponent: ViewComponent
    {
        private readonly SensorDbContext _context;

        public ListaClientesViewComponent(SensorDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var clientes = await _context.Clientes
                .Where(p => p.Activo == true)
                .ToListAsync();

            return View(clientes);
        }
    }
}

Sensor_App/Sensor_App/Views/User/Crear.cshtml
@model Sensor_App.Models.User
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPostUser(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label"></label>
                <input asp-for="Contrasenia" class="form-control" />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                @await Component.InvokeAsync("ListaClientes")
            </div>
            <div class="form-group">
                <label asp-for="Permisos" class="control-label"></label>
                <select class="permisos-multiple" name="Permisos[]" multiple="multiple">
                    <option value="0">Listado cliente</option>
                    <option value="1">Alta cliente</option>
                    <option value="2">Baja cliente</option>
                    <option value="3">Modificacion cliente</option>
                    <option value="4">Listado usuario</option>
                    <option value="5">Alta usuario</option>
                    <option value="6">Baja usuario</option>
                    <option value="7">Modificacion usuario</option>
                    <option value="8">Visualizacion mapa</option>
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/js/userAjax.js"></script>
<script>
    $(document).ready(function () {
        $('.cliente-select').select2();
    });
    $(document).ready(function () {
        $('.permisos-multiple').select2();
    });
</script>

Sensor_App/Sensor_App/Views/User/CrearOEditar.cshtml
@model Sensor_App.Models.User
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearOEditar" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label"></label>
                <input asp-for="Contrasenia" class="form-control" />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                @await Component.InvokeAsync("ListaClientes")
            </div>
            <div class="form-group">
                <label asp-for="Permisos" class="control-label"></label>
                <select class="permisos-multiple" name="Permisos[]" multiple="multiple">
                    <option value="0">Listado cliente</option>
                    <option value="1">Alta cliente</option>
                    <option value="2">Baja cliente</option>
                    <option value="3">Modificacion cliente</option>
                    <option value="4">Listado usuario</option>
                    <option value="5">Alta usuario</option>
                    <option value="6">Modificacion usuario</option>
                    <option value="7">Visualizacion mapa</option>
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/js/userAjax.js"></script>
<script>
    $(document).ready(function () {
        $('.cliente-select').select2();
    });
    $(document).ready(function () {
        $('.permisos-multiple').select2();
    });
</script>

Sensor_App/Sensor_App/Views/User/Editar.cshtml
@model Sensor_App.Models.User
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPostUser(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contrasenia" class="control-label"></label>
                <input asp-for="Contrasenia" class="form-control" />
                <span asp-validation-for="Contrasenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                @await Component.InvokeAsync("ListaClientes")
            </div>
            <div class="form-group">
                <label asp-for="Permisos" class="control-label"></label>
                <select class="permisos-multiple" name="Permisos[]" multiple="multiple">
                    <option value="0">Listado cliente</option>
                    <option value="1">Alta cliente</option>
                    <option value="2">Baja cliente</option>
                    <option value="3">Modificacion cliente</option>
                    <option value="4">Listado usuario</option>
                    <option value="5">Alta usuario</option>
                    <option value="6">Alta usuario</option>
                    <option value="7">Baja usuario</option>
                    <option value="8">Visualizacion mapa</option>
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/js/userAjax.js"></script>
<script>
    $(document).ready(function () {
        $('.cliente-select').select2();
    });
    $(document).ready(function () {
        $('.permisos-multiple').select2();
    });
</script>

Sensor_App/Sensor_App/Views/User/Inicio.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
@{
    ViewData["Title"] = "Inicio";
}

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <link href="~/assets/css/app.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->
</head>

<div class="row top30">
    <div class="col">
        <h1>Menu de inicio, para acceder a las funciones o ABM correspondientes debe de estar autenticado</h1>
    </div>
</div>
<p id="loginMessage" style="color: darkgreen;">
    Inicio sesion correctamente
</p>
<p id="logoutMessage" style="color: darkgreen;">
    Cerrado sesion correctamente
</p>

@if (httpContextAccessor.HttpContext.Session.GetString("LoginName") == null)
{
    <div class="row top30">
        <div class="col">
            <button type="button" id="loginButton" onclick="showInPopup('@Url.Action("LogIn","User", null, Context.Request.Scheme)', 'Login')" class="btn btn-primary btn-lg btn-block">Mostrar LogIn</button>
        </div>
    </div>
}


<div class="row top30">
    <div class="col">
        <button type="button" onclick="@("window.location.href='" + @Url.Action("ListaUsuarios", "User") + "'");" class="btn btn-primary btn-lg btn-block">Listado Usuarios y ABM</button>
    </div>
    <div class="col">
        <button type="button" onclick="@("window.location.href='" + @Url.Action("ListaClientes", "Cliente") + "'");" class="btn btn-primary btn-lg btn-block">Listado Clientes y ABM</button>
    </div>
    <div class="col">
        <button type="button" onclick="@("window.location.href='" + @Url.Action("Vermapa", "Mapa") + "'");" class="btn btn-primary btn-lg btn-block">Visualizacion en mapa de Marcadores</button>
    </div>
</div>
<!-- ================== BEGIN BASE JS ================== -->

<script src="~/js/theme/default.min.js"></script>

<!-- ================== END BASE JS ================== -->

Sensor_App/Sensor_App/Views/User/ListaUsuarios.cshtml
@model IEnumerable<Sensor_App.Models.User>

@{
    ViewData["Title"] = "Lista usuarios";
}
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <link href="~/assets/css/app.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->
</head>
<h1>Lista Usuarios</h1>

<p>
    <button type="button" class="btn btn-primary" id="crerUserButton" onclick="showInPopup('@Url.Action("Crear","User", null, Context.Request.Scheme)', 'Crear usuario')">Crear Usuario</button>
</p>

<div id="view-all">
    @await Html.PartialAsync("_VerUsuarios", Model)
</div>
<div>
    <button type="button" onclick="@("window.location.href='" + @Url.Action("Inicio", "User") + "'");" class="btn btn-primary">Volver a inicio</button>
</div>



<!-- ================== BEGIN BASE JS ================== -->

<script src="~/js/theme/default.min.js"></script>
<script src="~/js/site.js"></script>

<!-- ================== END BASE JS ================== -->

Sensor_App/Sensor_App/Views/User/LogIn.cshtml
@model Sensor_App.Models.LoginUserModel;
@{
    ViewData["Title"] = "Log In";
    Layout = null;
}

<head>
    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <link href="~/assets/css/app.min.css" rel="stylesheet" />
    <!-- ================== END BASE CSS STYLE ================== -->
</head>

<!-- begin login -->
<div class="login login-v1">
    <!-- begin login-container -->
    <div class="login-container">
        <!-- begin login-header -->
        <div class="login-header">
            <div class="brand">
                <span class="logo"></span> <b>LogIn</b> Sensor APP
                <small>Ingrese sus credenciales para iniciar sesion</small>
            </div>
        </div>
        <!-- end login-header -->
        <!-- begin login-body -->
        <div class="login-body">
            <!-- begin login-content -->
            <div class="login-content">

                <form id="loginForm">
                    <div class="form-group m-b-20">
                        <input type="text" id="userId" name="Usuario" class="form-control form-control-lg inverse-mode" placeholder="Usuario o Email" required />
                    </div>

                    <div class="form-group m-b-20">
                        <input type="password" id="passwordId" name="Contrasenia" class="form-control form-control-lg inverse-mode" placeholder="Password" required />
                    </div>

                    <div class="login-buttons">
                        <button id="btnSubmit" type="button" class="btn btn-success btn-block btn-lg" onclick="Login()">LogIn</button>
                    </div>
                </form>



            </div>
            <!-- end login-content -->
            <p id="msg" style="color: red;">Credenciales incorrectas
            </p>
        </div>
        <!-- end login-body -->
    </div>
    <!-- end login-container -->
</div>
<!-- end login -->
<!-- end page container -->
<!-- ================== BEGIN BASE JS ================== -->
<script src="~/js/site.js"></script>
<script src="~/js/theme/default.min.js"></script>

<!-- ================== END BASE JS ================== -->